# ITS IMVIS
# Chapter 6 - Vraag 2 OR operator
# Mike Rietveldt - 20183380

#In tabel
# X  Y | =
# 0  0 | 0 
# 0  1 | 1
# 1  0 | 1
# 1  1 | 1

# In een 3x3 waarin links allemeaal 1 en rechts allemaal 0 is krijg je natuurlijk een 3x3 met alleen maar enen.
# 3x3 Links         # 3x3 Rechts          # 3x3 Uitkomst  
# 1  1  1           # 0  0  0             # 1  1  1
# 1  1  1           # 0  0  0             # 1  1  1
# 1  1  1           # 0  0  0             # 1  1  1